name: 'CTO.ai GitHub Action'
description: 'The CTO.ai GitHub Action supports CTO.ai Lifecycle & Delivery Metrics'
inputs:
  token:
    description: 'Authorization Token'
    required: true
  team_id:
    description: 'Team ID'
    required: true
  url:
    description: 'Override Default Events API URL'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
