name: 'CTO.ai Github Action'
description: 'This action extends the Ops Platform Github App to allow users to send in additional events and details of their workflow'
inputs:
  token:
    description: 'Authorization Token'
    required: true
  team_id:
    description: 'Ops Platform team ID for team sending event.'
    required: true
  event_name:
    description: 'Name of the event i.e. "deployment"'
    required: true
  event_action:
    description: 'Outcome of event. Expecting one of: "succeeded", "failed", "initiated", "recovered"'
    required: true
  environment:
    description: 'Environment that workflow is running in i.e. "production"'
    required: false
  image:
    description: 'Built image ID'
    required: false
  branch:
    description: 'Overwrite branch specified by github in data payload (If not present, action will try to use ref value if available to event type)'
    required: false
  commit:
    description: 'Branch used to reference where change is taking place (If not present, action will try to use ref value if available to event type)'
    required: false
  repo:
    description: 'Repo used to reference where change is taking place (If not present, action will try to use the name of the repository the workflow is running in)'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
