#
# This agent will automatically record (some) CTO.ai Delivery & LifeCycle
# Metrics for use with the CTO.ai Delivery Metrics dashboard.
#
# Installation:
#
#   1. GitHub -> Settings -> Secrets -> New Secret
#     - Create CTOAI_TEAM_ID secret using your CTO.ai-issued Team Id.
#     - Create CTOAI_EVENTS_API_TOKEN secret using your CTO.ai-issued API Token.
#   2. Drop this file into your GitHub repository at your-repo/.github/workflows/ctoai-agent.yml
#
#       Done! Delivery & LifeCycle Metrics will now be available at your CTO.ai Dashboard.
#

on:
  create:
  delete:
  deployment_status:
  fork:
  gollum:
  issue_comment:
  issues:
  label:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  pull_request:
     types: [assigned, opened, synchronize, reopened, closed]
  pull_request_review:
  pull_request_review_comment:
  push:
  registry_package:
  release:
  status:
  watch:

jobs:
  ctoai-metrics:
    name: Record CTOai Delivery Metrics
    runs-on: ubuntu-latest
    steps:
    # This step is specific to our development in this repo as
    # This checkout step let's us run events from the local action code
    # You would not use this step as the action.yml is remote for you
    # See our other repos for a better example of how this is configured
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: "."
    - name: 'CTO.ai Delivery Metrics Agent Invocation'
      uses: ./ # You should use the cto-ai/action@version syntax here
      id: ctoai-agent
      with:
        team_id: ${{ secrets.CTOAI_TEAM_ID }}
        token: ${{ secrets.CTOAI_EVENTS_API_TOKEN }}
        # Change url if you want act to send to your local API during development
        # This will be set to our production API by default if you don't set it
        # url : https://api.cto.sh/api/v1/events
